name: Before release pull request

on:
  pull_request:
    types: [opened]
    

jobs:
  validate:
    name: Validation (release version)
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == false
    outputs:
      version: ${{ steps.check_version.outputs.version}}
    steps:
      - run: |
          if [[ ! $GITHUB_HEAD_REF =~ release\/v([0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}) ]]; then
            exit 1          
          fi
          v=${BASH_REMATCH[1]}
          echo "::notice file=pkg/consts/metadata.json::Current release ${v}"
          echo "version=${v}" >> $GITHUB_OUTPUT

  post-validate:
    name: Post Validation
    needs: [validate]
    if: needs.merged_release_version.outputs.version != ""
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "OK"

